apiVersion: litmuschaos.io/v1alpha1
kind: ChaosSchedule
metadata:
  name: sc-container-kill
spec:
  schedule:
    repeat:
      properties:
        #format should be like "10m" or "2h" accordingly for minutes or hours
        minChaosInterval: "10m"
  engineTemplateSpec:
    engineState: 'active'
    appinfo:
      appns: 'hipster-shop'
      applabel: 'product=hipster-shop'
      appkind: 'deployment'
    annotationCheck: 'false'
    chaosServiceAccount: pod-delete-sa
    jobCleanUpPolicy: 'delete'
    components:
      runner:
        runnerAnnotations:
          sidecar.istio.io/inject: "false"
    experiments:
      - name: container-kill
        spec:
          components:
            experimentAnnotations:
              sidecar.istio.io/inject: "false"
            env:
              # provide the total chaos duration
              - name: TOTAL_CHAOS_DURATION
                value: '500'

              # provide the chaos interval
              - name: CHAOS_INTERVAL
                value: '10'

              # provide the name of container runtime
              # for litmus LIB, it supports docker, containerd, crio
              # for pumba LIB, it supports docker only
              - name: CONTAINER_RUNTIME
                value: 'docker'

              # provide the socket file path
              - name: SOCKET_PATH
                value: '/var/run/docker.sock'

              - name: PODS_AFFECTED_PERC
                value: '50'

