apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: nodedrain-chaos-workflow-1642263175
  namespace: litmus
  labels:
    subject: nodedrain-chaos-workflow_litmus
spec:
  arguments:
    parameters:
      - name: adminModeNamespace
        value: litmus
  entrypoint: custom-chaos
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
    - name: custom-chaos
      steps:
        - - name: install-chaos-experiments
            template: install-chaos-experiments
        - - name: node-drain
            template: node-drain
        - - name: revert-chaos
            template: revert-chaos
    - name: install-chaos-experiments
      inputs:
        artifacts:
          - name: node-drain
            path: /tmp/node-drain.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                description:
                  message: |
                    Drain the node where application pod is scheduled
                kind: ChaosExperiment
                metadata:
                  name: node-drain
                  labels:
                    name: node-drain
                    app.kubernetes.io/part-of: litmus
                    app.kubernetes.io/component: chaosexperiment
                    app.kubernetes.io/version: 2.3.0
                spec:
                  definition:
                    scope: Cluster
                    permissions:
                      - apiGroups:
                          - ""
                        resources:
                          - pods
                        verbs:
                          - create
                          - delete
                          - get
                          - list
                          - patch
                          - update
                          - deletecollection
                      - apiGroups:
                          - ""
                        resources:
                          - events
                        verbs:
                          - create
                          - get
                          - list
                          - patch
                          - update
                      - apiGroups:
                          - ""
                        resources:
                          - configmaps
                        verbs:
                          - get
                          - list
                      - apiGroups:
                          - ""
                        resources:
                          - pods/log
                        verbs:
                          - get
                          - list
                          - watch
                      - apiGroups:
                          - ""
                        resources:
                          - pods/exec
                          - pods/eviction
                        verbs:
                          - get
                          - list
                          - create
                      - apiGroups:
                          - apps
                        resources:
                          - daemonsets
                        verbs:
                          - list
                          - get
                          - delete
                      - apiGroups:
                          - batch
                        resources:
                          - jobs
                        verbs:
                          - create
                          - list
                          - get
                          - delete
                          - deletecollection
                      - apiGroups:
                          - litmuschaos.io
                        resources:
                          - chaosengines
                          - chaosexperiments
                          - chaosresults
                        verbs:
                          - create
                          - list
                          - get
                          - patch
                          - update
                          - delete
                      - apiGroups:
                          - ""
                        resources:
                          - nodes
                        verbs:
                          - get
                          - list
                          - patch
                    image: litmuschaos/go-runner:2.3.0
                    imagePullPolicy: Always
                    args:
                      - -c
                      - ./experiments -name node-drain
                    command:
                      - /bin/bash
                    env:
                      - name: NODE_LABEL
                        value: "node-type=worker"
                      - name: TOTAL_CHAOS_DURATION
                        value: "60"
                      - name: LIB
                        value: litmus
                      - name: RAMP_TIME
                        value: ""
                    labels:
                      name: node-drain
                      app.kubernetes.io/part-of: litmus
                      app.kubernetes.io/component: experiment-job
                      app.kubernetes.io/version: 2.3.0
      container:
        args:
          - kubectl apply -f /tmp/node-drain.yaml -n
            {{workflow.parameters.adminModeNamespace}} |  sleep 30
        command:
          - sh
          - -c
        image: litmuschaos/k8s:latest
    - name: node-drain
      inputs:
        artifacts:
          - name: node-drain
            path: /tmp/chaosengine-node-drain.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                kind: ChaosEngine
                metadata:
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  generateName: node-drain
                  labels:
                    instance_id: 162ae44d-3005-4974-8c10-481171aa3b8c
                    context: node-drain_litmus
                spec:
                  engineState: active
                  auxiliaryAppInfo: ""
                  chaosServiceAccount: litmus-admin
                  experiments:
                    - name: node-drain
                      spec:
                        components:
                          env:
                            - name: TOTAL_CHAOS_DURATION
                              value: "600"
                            - name: NODE_LABEL
                              value: "node-type=worker"
                  annotationCheck: "false"
      container:
        args:
          - -file=/tmp/chaosengine-node-drain.yaml
          - -saveName=/tmp/engine-name
        image: litmuschaos/litmus-checker:latest
    - name: revert-chaos
      container:
        image: litmuschaos/k8s:latest
        command:
          - sh
          - -c
        args:
          - "kubectl delete chaosengine -l 'instance_id in
            (162ae44d-3005-4974-8c10-481171aa3b8c, )' -n
            {{workflow.parameters.adminModeNamespace}} "