apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: cpu-memory-chaos-workflow-1642263965
  namespace: litmus
  labels:
    subject: cpu-memory-chaos-workflow_litmus
spec:
  arguments:
    parameters:
      - name: adminModeNamespace
        value: litmus
  entrypoint: custom-chaos
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
    - name: custom-chaos
      steps:
        - - name: install-chaos-experiments
            template: install-chaos-experiments
        - - name: node-cpu-hog
            template: node-cpu-hog
          - name: node-memory-hog
            template: node-memory-hog
        - - name: revert-chaos
            template: revert-chaos
    - name: install-chaos-experiments
      inputs:
        artifacts:
          - name: node-cpu-hog
            path: /tmp/node-cpu-hog.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                description:
                  message: |
                    Give a cpu spike on a node belonging to a deployment
                kind: ChaosExperiment
                metadata:
                  name: node-cpu-hog
                  labels:
                    name: node-cpu-hog
                    app.kubernetes.io/part-of: litmus
                    app.kubernetes.io/component: chaosexperiment
                    app.kubernetes.io/version: 2.3.0
                spec:
                  definition:
                    scope: Cluster
                    permissions:
                      - apiGroups:
                          - ""
                        resources:
                          - pods
                        verbs:
                          - create
                          - delete
                          - get
                          - list
                          - patch
                          - update
                          - deletecollection
                      - apiGroups:
                          - ""
                        resources:
                          - events
                        verbs:
                          - create
                          - get
                          - list
                          - patch
                          - update
                      - apiGroups:
                          - ""
                        resources:
                          - configmaps
                        verbs:
                          - get
                          - list
                      - apiGroups:
                          - ""
                        resources:
                          - pods/log
                        verbs:
                          - get
                          - list
                          - watch
                      - apiGroups:
                          - ""
                        resources:
                          - pods/exec
                        verbs:
                          - get
                          - list
                          - create
                      - apiGroups:
                          - batch
                        resources:
                          - jobs
                        verbs:
                          - create
                          - list
                          - get
                          - delete
                          - deletecollection
                      - apiGroups:
                          - litmuschaos.io
                        resources:
                          - chaosengines
                          - chaosexperiments
                          - chaosresults
                        verbs:
                          - create
                          - list
                          - get
                          - patch
                          - update
                          - delete
                      - apiGroups:
                          - ""
                        resources:
                          - nodes
                        verbs:
                          - get
                          - list
                    image: litmuschaos/go-runner:2.3.0
                    imagePullPolicy: Always
                    args:
                      - -c
                      - ./experiments -name node-cpu-hog
                    command:
                      - /bin/bash
                    env:
                      - name: TOTAL_CHAOS_DURATION
                        value: "60"
                      - name: RAMP_TIME
                        value: ""
                      - name: NODE_CPU_CORE
                        value: "2"
                      - name: NODE_LABEL
                        value: "node-type=worker"
                      - name: LIB
                        value: litmus
                      - name: LIB_IMAGE
                        value: litmuschaos/go-runner:2.3.0
                      - name: NODES_AFFECTED_PERC
                        value: "30"
                      - name: SEQUENCE
                        value: parallel
                    labels:
                      name: node-cpu-hog
                      app.kubernetes.io/part-of: litmus
                      app.kubernetes.io/component: experiment-job
                      app.kubernetes.io/version: 2.3.0
          - name: node-memory-hog
            path: /tmp/node-memory-hog.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                description:
                  message: |
                    Give a memory hog on a node belonging to a deployment
                kind: ChaosExperiment
                metadata:
                  name: node-memory-hog
                  labels:
                    name: node-memory-hog
                    app.kubernetes.io/part-of: litmus
                    app.kubernetes.io/component: chaosexperiment
                    app.kubernetes.io/version: 2.3.0
                spec:
                  definition:
                    scope: Cluster
                    permissions:
                      - apiGroups:
                          - ""
                        resources:
                          - pods
                        verbs:
                          - create
                          - delete
                          - get
                          - list
                          - patch
                          - update
                          - deletecollection
                      - apiGroups:
                          - ""
                        resources:
                          - events
                        verbs:
                          - create
                          - get
                          - list
                          - patch
                          - update
                      - apiGroups:
                          - ""
                        resources:
                          - configmaps
                        verbs:
                          - get
                          - list
                      - apiGroups:
                          - ""
                        resources:
                          - pods/log
                        verbs:
                          - get
                          - list
                          - watch
                      - apiGroups:
                          - ""
                        resources:
                          - pods/exec
                        verbs:
                          - get
                          - list
                          - create
                      - apiGroups:
                          - batch
                        resources:
                          - jobs
                        verbs:
                          - create
                          - list
                          - get
                          - delete
                          - deletecollection
                      - apiGroups:
                          - litmuschaos.io
                        resources:
                          - chaosengines
                          - chaosexperiments
                          - chaosresults
                        verbs:
                          - create
                          - list
                          - get
                          - patch
                          - update
                          - delete
                      - apiGroups:
                          - ""
                        resources:
                          - nodes
                        verbs:
                          - get
                          - list
                    image: litmuschaos/go-runner:2.3.0
                    imagePullPolicy: Always
                    args:
                      - -c
                      - ./experiments -name node-memory-hog
                    command:
                      - /bin/bash
                    env:
                      - name: TOTAL_CHAOS_DURATION
                        value: "120"
                      - name: MEMORY_CONSUMPTION_PERCENTAGE
                        value: "40"
                      - name: MEMORY_CONSUMPTION_MEBIBYTES
                        value: ""
                      - name: NUMBER_OF_WORKERS
                        value: "1"
                      - name: NODE_LABEL
                        value: "node-type=worker"
                      - name: RAMP_TIME
                        value: ""
                      - name: LIB
                        value: litmus
                      - name: LIB_IMAGE
                        value: litmuschaos/go-runner:2.3.0
                      - name: NODES_AFFECTED_PERC
                        value: ""
                      - name: SEQUENCE
                        value: parallel
                    labels:
                      name: node-memory-hog
                      app.kubernetes.io/part-of: litmus
                      app.kubernetes.io/component: experiment-job
                      app.kubernetes.io/version: 2.3.0
      container:
        args:
          - kubectl apply -f /tmp/node-memory-hog.yaml -n
            {{workflow.parameters.adminModeNamespace}} |  sleep 30
        command:
          - sh
          - -c
        image: litmuschaos/k8s:latest
    - name: node-cpu-hog
      inputs:
        artifacts:
          - name: node-cpu-hog
            path: /tmp/chaosengine-node-cpu-hog.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                kind: ChaosEngine
                metadata:
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  generateName: node-cpu-hog
                  labels:
                    instance_id: 5ef50e1b-a62d-4ed1-84a3-5914a939fe32
                    context: node-cpu-hog_litmus
                spec:
                  engineState: active
                  auxiliaryAppInfo: ""
                  chaosServiceAccount: litmus-admin
                  experiments:
                    - name: node-cpu-hog
                      spec:
                        components:
                          env:
                            - name: TOTAL_CHAOS_DURATION
                              value: "300"
                            - name: NODE_CPU_CORE
                              value: "1"
                            - name: NODES_AFFECTED_PERC
                              value: "40"
                            - name: NODE_LABEL
                              value: "node-type=worker"
                  annotationCheck: "false"
      container:
        args:
          - -file=/tmp/chaosengine-node-cpu-hog.yaml
          - -saveName=/tmp/engine-name
        image: litmuschaos/litmus-checker:latest
    - name: node-memory-hog
      inputs:
        artifacts:
          - name: node-memory-hog
            path: /tmp/chaosengine-node-memory-hog.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                kind: ChaosEngine
                metadata:
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  generateName: node-memory-hog
                  labels:
                    instance_id: 5b9bfa87-fc2b-4e03-8eb0-f05284e23330
                    context: node-memory-hog_litmus
                spec:
                  engineState: active
                  auxiliaryAppInfo: ""
                  chaosServiceAccount: litmus-admin
                  experiments:
                    - name: node-memory-hog
                      spec:
                          env:
                            - name: TOTAL_CHAOS_DURATION
                              value: "300"
                            - name: MEMORY_CONSUMPTION_PERCENTAGE
                              value: "30"
                            - name: NODES_AFFECTED_PERC
                              value: "40"
                            - name: TARGET_NODES
                              value: ""
                            - name: NODE_LABEL
                              value: "node-type=worker"
                  annotationCheck: "false"
      container:
        args:
          - -file=/tmp/chaosengine-node-memory-hog.yaml
          - -saveName=/tmp/engine-name
        image: litmuschaos/litmus-checker:latest
    - name: revert-chaos
      container:
        image: litmuschaos/k8s:latest
        command:
          - sh
          - -c
        args:
          - "kubectl delete chaosengine -l 'instance_id in
            (5ef50e1b-a62d-4ed1-84a3-5914a939fe32,
            5b9bfa87-fc2b-4e03-8eb0-f05284e23330, )' -n
            {{workflow.parameters.adminModeNamespace}} "
  podGC:
    strategy: OnWorkflowCompletion
